spring.application.name=bookstore
server.port=8989
spring.mongodb.uri=mongodb://localhost:27017/bookstore
#spring.mongodb.uri=mongodb+srv://2061abhishek_db_user:kYQRIk02RULDs0Ki@cluster0.ewrbeln.mongodb.net/?appName=Cluster0
spring.mongodb.database=bookstore
